Update PPP
AY2324S1-CS2103-T16-3/tp pull request #183
Opened 2023-11-08 11:39 UTC by jamz903

2023-11-08 13:55 UTC, woojiahao requested changes
Awesome @jamz903 Do you want to update your about me role/responsibilities too? Also minor spelling nit

2023-11-08 13:55 UTC, woojiahao commented on docs/team/jamz903.md
> +    * Enhance Style & Display of Ui to match prototype [[PR #76]](https://github.com/AY2324S1-CS2103-T16-3/tp/pull/76)
```suggestion
    * Enhance Style & Display of UI to match prototype [[PR #76]](https://github.com/AY2324S1-CS2103-T16-3/tp/pull/76)
```

2023-11-08 13:55 UTC, woojiahao commented on docs/team/jamz903.md
> +    * Enhance Style & Display of Ui to match prototype [[PR #76]](https://github.com/AY2324S1-CS2103-T16-3/tp/pull/76)
Super minor nit haha

2023-11-08 15:37 UTC, woojiahao approved these changes
LGTM

2023-11-08 16:17 UTC, sp4ce-cowboy approved these changes
LGTM, appreciate the shout out! Btw I think you can add refactor UI as well (in the new features part), since you did the initial refactoring from AB3 to UniCa$h (and the UI Mockup), in my PPP I'll credit you as well for the UI refactoring.

2023-11-09 13:28 UTC, sp4ce-cowboy approved these changes
LGTM!

2023-11-09 13:29 UTC, merged